import type { Notification } from "./types"

export const mockNotifications: Notification[] = [
  {
    id: "1",
    type: "transfer_in",
    title: "Recibiste $2,500.00",
    description: "De María López · Pago compartido",
    time: "Hace 5 min",
    read: false,
  },
  {
    id: "2",
    type: "friend_request",
    title: "Solicitud de amistad",
    description: "Valentina Ortiz quiere conectar contigo",
    time: "Hace 20 min",
    read: false,
  },
  {
    id: "3",
    type: "transfer_out",
    title: "Enviaste $450.00",
    description: "A Carlos Ruiz · Comida",
    time: "Hace 1 hr",
    read: false,
  },
  {
    id: "4",
    type: "security",
    title: "Inicio de sesión nuevo",
    description: "Se detectó un acceso desde Chrome en Windows",
    time: "Hace 3 hrs",
    read: true,
  },
  {
    id: "5",
    type: "transfer_in",
    title: "Recibiste $1,200.00",
    description: "De Pedro Sánchez · Renta",
    time: "Ayer",
    read: true,
  },
  {
    id: "6",
    type: "promo",
    title: "¡Nuevo beneficio disponible!",
    description: "Activa cashback del 5% en tus compras",
    time: "Ayer",
    read: true,
  },
  {
    id: "7",
    type: "transfer_out",
    title: "Enviaste $3,800.00",
    description: "A Diego Torres · Servicios",
    time: "Lun",
    read: true,
  },
  {
    id: "8",
    type: "friend_request",
    title: "Nueva conexión",
    description: "Ahora eres amigo de Ana García",
    time: "Dom",
    read: true,
  },
]
